'use strict';

exports.__esModule = true;
var namespace = 'DRAWER';

var ON_DRAWER_OPEN_CHANGED = exports.ON_DRAWER_OPEN_CHANGED = namespace + '@ON_DRAWER_OPEN_CHANGED';
var ON_DRAWER_MOBILE_OPEN_CHANGED = exports.ON_DRAWER_MOBILE_OPEN_CHANGED = namespace + '@ON_DRAWER_MOBILE_OPEN_CHANGED';
var ON_DRAWER_USE_MINIFIED_CHANGED = exports.ON_DRAWER_USE_MINIFIED_CHANGED = namespace + '@ON_DRAWER_USE_MINIFIED_CHANGED';